server:
  port: 9200
spring:
  rabbitmq:
#    host: 192.168.0.148
    host: 192.168.0.41
    port: 5672
    username: guest
    password: guest
remote:
  host: ${REMOTE-HOST:192.168.0.197}
  port: ${REMOTE-PORT:9996}

data:
  logdebug: true