server:
  port: 9090


spring:
  rabbitmq:
#    host: 192.168.0.148
    host: 192.168.0.41
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 200

web:
  service:
    url: http://%s:%s/wj/waterserver
    publishIp: 0.0.0.0
    publishPort: 9990
    zyws_url: http://%s:%s/wj/zywsSever